In [1]:
import numpy as np
import math 

lst1 = [1,2,3]
arr1 = np.array(lst1,dtype=np.uint8)
type(lst1)
type(arr1)

arr2 = np.array([[1,2,3],[4,5,6]],dtype=np.int16)
arr2

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,0,0]],[[-1,-1,-1],[1,1,1]]],np.int16)
arr3

'''
This is 1 demensional array
'''
arr1[0], arr1[1],arr1[2]
arr1[-1], arr1[-2],#arr1[3] errors out of bounds

'''
This is 2 demensional array
'''
arr2[0,0],arr2[0,1],arr2[0,2]

'''entire row and entire column'''
arr2[0,:]
arr2[1,:]

arr2[:,0]
arr2[:,1]

arr3[0,0,0]
arr3[1,1,2]
arr3[:,1,1]

array([5, 0, 1], dtype=int16)

In [47]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0,  0,  0]],

       [[-1, -1, -1],
        [ 1,  1,  1]]], dtype=int16)

In [45]:
x2 = np.array([[[1,2,3],[4,5,6]],[[0,-1,-2],[-3,-4,-5]]],np.int16)
x2.ndim, x2.shape, x2.dtype

(3, (2, 2, 3), dtype('int16'))

In [42]:
x2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]], dtype=int16)

In [53]:
print(np.inf)
print(np.nan)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)
print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [16]:
floatArr = np.array([0.,1.,2.,3.,4.,5.,6.])
strArr = np.array(['A','B','C'])
arange = np.arange(8,dtype=np.float32)

print(floatArr)
print(strArr)
print(arange)

[0. 1. 2. 3. 4. 5. 6.]
['A' 'B' 'C']
[0. 1. 2. 3. 4. 5. 6. 7.]


In [17]:

print("original",floatArr)
print("sum",floatArr.sum())
print("std deveation",floatArr.std())
print("cumulative sum",floatArr.cumsum())

original [0. 1. 2. 3. 4. 5. 6.]
sum 21.0
std deveation 2.0
cumulative sum [ 0.  1.  3.  6. 10. 15. 21.]


In [31]:
#scalar multiplication
print([1.,2.,3.,4.])
print([1.,2.,3.,4.] * 2)

#proper Scalar multiplication
print("-----------------------")
print(floatArr)
print("times 2",floatArr*2)
print("power 2",floatArr**2)
print("power x",floatArr**floatArr)
print("exp",np.exp(floatArr))
print("sqrt",np.sqrt(floatArr))

%timeit np.sqrt(2.5)
%timeit math.sqrt(2.5)

[1.0, 2.0, 3.0, 4.0]
[1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0, 4.0]
-----------------------
[0. 1. 2. 3. 4. 5. 6.]
times 2 [ 0.  2.  4.  6.  8. 10. 12.]
power 2 [ 0.  1.  4.  9. 16. 25. 36.]
power x [1.0000e+00 1.0000e+00 4.0000e+00 2.7000e+01 2.5600e+02 3.1250e+03
 4.6656e+04]
exp [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591  403.42879349]
sqrt [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974]
743 ns ± 67 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
71.1 ns ± 1.39 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [39]:
b = np.array([floatArr,floatArr*2])
print(b[0])
print(b[0,2])
print(b[:,1])
print(b.sum())
#sum either by row or column 
print(b.sum(axis=0))
print(b.sum(axis=1))

[0. 1. 2. 3. 4. 5. 6.]
2.0
[1. 2.]
63.0
[ 0.  3.  6.  9. 12. 15. 18.]
[21. 42.]


In [49]:
c = np.zeros((2,3),dtype="f")
print(c)
c = np.ones((2,3,4),dtype="f")
print(c)

d = np.zeros_like(c,dtype="f")
print(d)

d = np.ones_like(c,dtype="f")
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [21]:
# Sructured numpyArray
dt = np.dtype([("Name","S10"),("Age","i4"),("Height","f"),("Children/Pets","i4",2)])
print(dt)

dt = np.dtype({"names":["Name","Age","Height","Children/Pet"],
               "formats":"O int float int,int".split()})

print(dt)
dt = np.dtype([("Name","O"),("Age","<i8"),("Height","<f8"),("Children/Pet",[("f0","<i8"),("f1","<i8")])])
print(dt)

s = np.array([("Smith",45,1.83,(0,1)),
              ("Jones",53,1.72,(2,2))],dtype=dt)
print(s)

print("Name", s["Name"])
print("Height", s["Height"])
print("Height Mean", s["Height"].mean())
print("first element",s[0])
print("Age", s[1]["Age"])

[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))]
[('Name', 'O'), ('Age', '<i4'), ('Height', '<f8'), ('Children/Pet', [('f0', '<i4'), ('f1', '<i4')])]
[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pet', [('f0', '<i8'), ('f1', '<i8')])]
[('Smith', 45, 1.83, (0, 1)) ('Jones', 53, 1.72, (2, 2))]
Name ['Smith' 'Jones']
Height [1.83 1.72]
Height Mean 1.775
first element ('Smith', 45, 1.83, (0, 1))
Age 53


In [29]:
# Vectorizaion
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * .5

print("R:",r)
print("S:",s)

print("R+S:",r+s)

R: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
S: [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]
 [4.5 5.  5.5]]
R+S: [[ 0.   1.5  3. ]
 [ 4.5  6.   7.5]
 [ 9.  10.5 12. ]
 [13.5 15.  16.5]]


In [30]:
print("R+3\n",r+3)

R+3
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [31]:
print("R*2\n",r*2)

R*2
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [32]:
print("2*R+3\n",2*r+3)

2*R+3
 [[ 3  5  7]
 [ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [47]:
x = np.random.standard_normal((1000000,5))
y = 2 * x + 3
C = np.array((x,y),order='C')
F = np.array((x,y),order='F')
x = 0.0; y = 0.0
C[:2].round(2)


array([[[-1.48,  1.91,  0.84, -1.13,  0.11],
        [-0.55, -0.09, -1.19, -0.03, -1.88],
        [ 0.43, -0.28, -0.36, -0.53, -1.67],
        ...,
        [ 0.4 ,  0.47, -0.04,  0.42, -1.52],
        [ 1.03, -1.72, -0.51,  0.62, -2.04],
        [ 0.03,  0.64, -0.58, -0.03, -0.1 ]],

       [[ 0.04,  6.81,  4.68,  0.74,  3.22],
        [ 1.91,  2.82,  0.61,  2.93, -0.75],
        [ 3.87,  2.45,  2.28,  1.95, -0.33],
        ...,
        [ 3.8 ,  3.95,  2.91,  3.83, -0.04],
        [ 5.07, -0.45,  1.98,  4.24, -1.07],
        [ 3.06,  4.27,  1.84,  2.93,  2.8 ]]])